ZEPTO INVENTORY ANALYSIS

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Walmart.csv")

In [3]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [4]:
df.shape

(10051, 11)

In [5]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [7]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

Replace the null value with category based median

In [8]:
df[df['unit_price'].isnull()]

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
1892,1893,WALM024,Carrollton,Home and lifestyle,NaN,NaN,09/06/23,16:09:00,Ewallet,9.0,0.48
1893,1894,WALM009,Plano,Fashion accessories,NaN,NaN,02/08/22,22:11:00,Ewallet,4.0,0.48
1894,1895,WALM010,Laredo,Home and lifestyle,NaN,NaN,01/08/23,12:06:00,Ewallet,4.0,0.48
1895,1896,WALM069,Rockwall,Fashion accessories,NaN,NaN,21/07/23,15:49:00,Ewallet,4.0,0.33
1896,1897,WALM093,Angleton,Home and lifestyle,NaN,NaN,15/05/22,12:36:00,Ewallet,9.0,0.33
1897,1898,WALM098,Mineral Wells,Fashion accessories,NaN,NaN,01/11/23,10:08:00,Ewallet,4.0,0.18
1898,1899,WALM009,Plano,Home and lifestyle,NaN,NaN,01/10/21,13:05:00,Ewallet,6.0,0.48
1899,1900,WALM071,Lufkin,Fashion accessories,NaN,NaN,19/05/21,8:36:00,Ewallet,7.0,0.33
1900,1901,WALM090,Brownwood,Home and lifestyle,NaN,NaN,13/02/21,14:50:00,Ewallet,8.0,0.33
1901,1902,WALM067,Haltom City,Fashion accessories,NaN,NaN,15/05/22,19:20:00,Ewallet,8.0,0.33
1902,1903,WALM033,Pearland,Home and lifestyle,NaN,NaN,28/08/22,15:37:00,Ewallet,4.0,0.48
1903,1904,WALM018,Frisco,Fashion accessories,NaN,NaN,21/04/22,18:30:00,Ewallet,4.0,0.48
1904,1905,WALM076,Huntsville,Home and lifestyle,NaN,NaN,02/03/20,14:33:00,Ewallet,4.0,0.33
1905,1906,WALM010,Laredo,Fashion accessories,NaN,NaN,20/08/21,14:25:00,Ewallet,5.0,0.48
1906,1907,WALM030,Richardson,Home and lifestyle,NaN,NaN,14/12/23,18:12:00,Ewallet,8.0,0.48
1907,1908,WALM001,Houston,Fashion accessories,NaN,NaN,09/08/22,12:46:00,Ewallet,9.0,0.36
1908,1909,WALM096,Eagle Pass,Home and lifestyle,NaN,NaN,23/11/21,18:26:00,Ewallet,9.0,0.33
1909,1910,WALM085,Kerrville,Fashion accessories,NaN,NaN,24/08/22,11:53:00,Ewallet,4.0,0.33
1910,1911,WALM040,Edinburg,Home and lifestyle,NaN,NaN,27/07/20,21:38:00,Ewallet,9.0,0.48
1911,1912,WALM080,Nacogdoches,Fashion accessories,NaN,NaN,15/10/20,8:01:00,Ewallet,7.0,0.33
1912,1913,WALM068,Burleson,Home and lifestyle,NaN,NaN,31/07/23,9:20:00,Ewallet,6.0,0.33
1913,1914,WALM048,Harlingen,Fashion accessories,NaN,NaN,28/02/21,18:47:00,Ewallet,7.0,0.48
1914,1915,WALM018,Frisco,Home and lifestyle,NaN,NaN,19/04/23,16:12:00,Ewallet,7.0,0.48
1915,1916,WALM015,Grand Prairie,Fashion accessories,NaN,NaN,11/08/21,21:28:00,Ewallet,5.0,0.48
1916,1917,WALM041,Mission,Home and lifestyle,NaN,NaN,25/06/23,13:15:00,Ewallet,6.0,0.48
1917,1918,WALM045,Missouri City,Fashion accessories,NaN,NaN,11/01/20,10:27:00,Credit card,5.0,0.48
1918,1919,WALM011,Lubbock,Home and lifestyle,NaN,NaN,01/08/22,14:40:00,Ewallet,8.0,0.48
1919,1920,WALM052,Mansfield,Fashion accessories,NaN,NaN,09/04/21,12:04:00,Ewallet,5.0,0.57
1920,1921,WALM022,Mesquite,Home and lifestyle,NaN,NaN,21/03/20,18:16:00,Ewallet,6.0,0.48
1921,1922,WALM024,Carrollton,Fashion accessories,NaN,NaN,16/03/21,15:39:00,Ewallet,8.0,0.48
1922,1923,WALM070,Hurst,Home and lifestyle,NaN,NaN,30/10/20,18:39:00,Ewallet,5.0,0.33

In [9]:
# First, clean the unit_price column by removing '$' and converting to float
df['unit_price'] = df['unit_price'].str.replace('$', '', regex=False).astype(float)

# Then fill null values with category-based median
df['unit_price'] = df.groupby('category')['unit_price'].transform(lambda x: x.fillna(x.median()))

In [10]:
df['quantity'].unique()

array([ 7.,  5.,  8.,  6., 10.,  2.,  3.,  4.,  1.,  9., nan])

In [11]:
df['quantity'] = df.groupby('category')['quantity'].transform(lambda x:x.fillna(x.median()))

In [12]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [13]:
df.iloc[1892]

invoice_id                      1893
Branch                       WALM024
City                      Carrollton
category          Home and lifestyle
unit_price                      51.0
quantity                         2.0
date                        09/06/23
time                        16:09:00
payment_method               Ewallet
rating                           9.0
profit_margin                   0.48
Name: 1892, dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10051 non-null  float64
 5   quantity        10051 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(4), int64(1), object(6)
memory usage: 863.9+ KB

Data validation -> change the data type format for date and time.

In [15]:
df['date'] = pd.to_datetime(df['date'])
df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S').dt.time

C:\Users\ananya\AppData\Local\Temp\ipykernel_21636\2341293245.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date'] = pd.to_datetime(df['date'])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10051 non-null  float64
 5   quantity        10051 non-null  float64
 6   date            10051 non-null  datetime64[ns]
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(5)
memory usage: 863.9+ KB

In [17]:
df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S')

In [18]:
print(df['time'])

0       1900-01-01 13:08:00
1       1900-01-01 10:29:00
2       1900-01-01 13:23:00
3       1900-01-01 20:33:00
4       1900-01-01 10:37:00
                ...
10046   1900-01-01 10:10:00
10047   1900-01-01 14:20:00
10048   1900-01-01 16:00:00
10049   1900-01-01 12:25:00
10050   1900-01-01 09:48:00
Name: time, Length: 10051, dtype: datetime64[ns]

In [19]:
print(df['time'].dtype)

datetime64[ns]

In [20]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [21]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,2019-05-01,1900-01-01 13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,2019-08-03,1900-01-01 10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,2019-03-03,1900-01-01 13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,2019-01-27,1900-01-01 20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,2019-08-02,1900-01-01 10:37:00,Ewallet,5.3,0.48

In [22]:
df['total_price'] = df['quantity']*df['unit_price']

In [23]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total_price
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,2019-05-01,1900-01-01 13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,2019-08-03,1900-01-01 10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,2019-03-03,1900-01-01 13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,2019-01-27,1900-01-01 20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,2019-08-02,1900-01-01 10:37:00,Ewallet,5.3,0.48,604.17

In [27]:
df.columns = df.columns.str.lower()

In [29]:
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin',
       'total_price'],
      dtype='object')

Connecting with the database

In [30]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:postgres@localhost:5432/walmart_db")

In [31]:
df.to_sql("walmart", engine, if_exists="replace", index=False)

51